version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    expose:
      - "5672"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - labs

networks:
  labs:
    driver: "bridge"
