app:
  version: 1.0.0
  title: Labs
  paths:
    v1: /v1

server:
  port: 8081
  servlet:
    context-path: /api
---
spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application:
    name: labs
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

queue-service:
  write: labs_posts
  listener: labs_subscribes
  exchange: labs
  route-key: posts-route